packages:
  - vue
  - browseruse-mcp/*
  - configs/*
  - shared
  - external
  - types
  - psdk/*
  - ext/*
  - req
  - ui

catalog:
  '@changesets/cli': ^2.29.7
  '@date-io/dayjs': ^3.2.0
  '@tsconfig/node22': ^22.0.2
  '@varlet/ui': ^3.12.1
  autoprefixer: ^10.4.22
  dayjs: ^1.11.19
  element-plus: ^2.11.7
  libarchive.js: ^2.0.2
  lodash-es: ^4.17.21
  npm: ^11.6.2
  npm-run-all2: ^8.0.4
  pdfjs-dist: ^5.4.394
  pnpm: ^10.21.0
  prettier: ^3.6.2
  sass: ^1.94.0
  turbo: ^2.6.1
  typescript: ^5.9.3
  unplugin-auto-import: ^20.2.0
  unplugin-fonts: ^1.4.0
  unplugin-vue-components: ^30.0.0
  unplugin-vue-router: ^0.16.1
  yarn: ^1.22.22

catalogs:
  chrome:
    '@types/chrome': ^0.1.27
    chrome-launcher: ^1.2.1
    lighthouse: ^13.0.1
  cssnano:
    cssnano: ^7.1.2
    cssnano-preset-advanced: ^7.0.10
  eslint:
    '@antfu/eslint-config': ^6.2.0
    '@eslint/js': ^9.39.1
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-vue: ^10.5.1
    typescript-eslint: ^8.46.4
  gulp:
    '@types/gulp': ^4.0.18
    '@types/gulp-autoprefixer': ^0.0.37
    '@types/gulp-postcss': ^8.0.6
    '@types/gulp-sass': ^6.0.0
    gulp: ^5.0.1
    gulp-postcss: ^10.0.0
    gulp-sass: ^6.0.1
  iconify:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/flag': ^1.2.10
    '@iconify-json/fluent': ^1.2.34
    '@iconify-json/ion': ^1.2.6
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/simple-icons': ^1.2.58
  mcp:
    '@modelcontextprotocol/sdk': ^1.21.1
    llm-cost: ^1.0.5
    puppeteer-core: ^24.29.1
  node:
    '@types/body-parser': ^1.19.6
    '@types/cors': ^2.8.19
    '@types/express': ^5.0.5
    '@types/node': ^24.10.0
    '@types/ws': ^8.18.1
    body-parser: ^2.2.0
    cors: ^2.8.5
    express: ^5.1.0
    pino: ^10.1.0
    ws: ^8.18.3
  rollup:
    rollup: ^4.53.2
  tsdown:
    tsdown: ^0.16.2
    unplugin-vue: ^7.0.4
    unplugin-vue-jsx: ^0.6.1
  types:
    '@types/lodash-es': ^4.17.12
  unocss:
    '@unocss/cli': ^66.5.6
    '@unocss/eslint-config': ^66.5.6
    '@unocss/postcss': ^66.5.6
    '@unocss/transformer-attributify-jsx': ^66.5.6
    '@unocss/transformer-compile-class': ^66.5.6
    unocss: ^66.5.6
  vee-validate:
    '@vee-validate/yup': ^4.15.1
    '@vee-validate/zod': ^4.15.1
    vee-validate: ^4.15.1
    yup: ^1.7.1
    zod: ^4.1.12
  vite:
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    vite: ^7.2.2
    vite-plugin-dts: ^4.5.4
    vite-plugin-vue-devtools: ^8.0.3
  vitest:
    '@types/jsdom': ^27.0.0
    happy-dom: ^20.0.10
    jsdom: ^27.1.0
    vitest: ^4.0.8
  vue:
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    vue: ^3.5.24
    vue-router: ^4.6.3
    vue-tsc: ^3.1.3
  vuetify:
    '@mdi/font': ^7.4.47
    vite-plugin-vuetify: ^2.1.2
    vuetify: ^3.10.10
  vueuse:
    '@vueuse/core': ^14.0.0
