packages:
  - 'configs/*'
  - shared
  - external
  - types
  - 'psdk/*'
  - 'ext/*'
  - req
  - ui
catalog:
  '@antfu/eslint-config': ^4.13.0
  '@antfu/ni': ^24.3.0
  '@babel/types': ^7.27.1
  '@date-io/date-fns': ^3.2.1
  '@date-io/dayjs': ^3.2.0
  '@dcloudio/types': ^3.4.15
  '@dcloudio/uni-app': 3.0.0-alpha-4000020231218001
  '@edge-runtime/vm': ^5.0.0
  '@eslint/js': ^9.26.0
  '@iconify-json/ant-design': ^1.2.5
  '@iconify-json/flag': ^1.2.5
  '@iconify-json/fluent': ^1.2.20
  '@iconify-json/ion': ^1.2.3
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/simple-icons': ^1.2.33
  '@mdi/font': ^7.4.47
  '@playwright/test': ^1.52.0
  '@quasar/extras': ^1.16.17
  '@quasar/vite-plugin': ^1.9.0
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': ^28.0.3
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-multi-entry': ^6.0.1
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^12.1.2
  '@rollup/rollup-win32-x64-msvc': ^4.40.2
  '@rushstack/eslint-patch': ^1.11.0
  '@stomp/stompjs': ^7.1.1
  '@tsconfig/node18': ^18.2.4
  '@tsconfig/node20': ^20.1.5
  '@tsconfig/node22': ^22.0.1
  '@types/chrome': ^0.0.321
  '@types/fs-extra': ^11.0.4
  '@types/gulp': ^4.0.17
  '@types/gulp-autoprefixer': ^0.0.37
  '@types/gulp-postcss': ^8.0.6
  '@types/gulp-sass': ^5.0.4
  '@types/jsdom': ^21.1.7
  '@types/lodash': ^4.17.16
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.15.17
  '@types/qs': ^6.9.18
  '@types/sockjs-client': ^1.5.4
  '@types/stompjs': ^2.3.9
  '@types/through2': ^2.0.41
  '@types/ws': ^8.18.1
  '@typescript-eslint/parser': ^8.32.0
  '@unocss/cli': ^66.1.1
  '@unocss/core': ^66.1.1
  '@unocss/eslint-config': ^66.1.1
  '@unocss/postcss': ^66.1.1
  '@unocss/transformer-attributify-jsx': ^66.1.1
  '@unocss/transformer-compile-class': ^66.1.1
  '@unocss/transformer-directives': ^66.1.1
  '@varlet/ui': ^3.10.6
  '@vee-validate/yup': ^4.15.0
  '@vee-validate/zod': ^4.15.0
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.1.2
  '@vue/compiler-dom': ^3.5.13
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.5.0
  '@vue/runtime-core': ^3.5.13
  '@vue/runtime-dom': ^3.5.13
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.1.0
  '@vueuse/shared': ^13.1.0
  autoprefixer: ^10.4.21
  command-line-args: ^6.0.1
  command-line-usage: ^7.0.3
  core-js: ^3.42.0
  cssnano: ^7.0.7
  cssnano-preset-advanced: ^7.0.7
  dayjs: ^1.11.13
  element-plus: ^2.9.10
  eslint: ^9.26.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-oxlint: ^0.16.10
  eslint-plugin-prettier: ^5.4.0
  eslint-plugin-vue: ^10.1.0
  fs-extra: ^11.3.0
  globals: ^16.1.0
  gulp: ^5.0.0
  gulp-autoprefixer: ^9.0.0
  gulp-clean: ^0.4.0
  gulp-postcss: ^10.0.0
  gulp-rimraf: ^1.0.0
  gulp-sass: ^6.0.1
  gulp-scss: ^1.4.0
  highlight.js: ^11.11.1
  jsdom: ^26.1.0
  jszip: ^3.10.1
  libarchive.js: ^2.0.2
  lodash-es: ^4.17.21
  mini-types: ^0.1.7
  miniprogram-api-typings: ^4.0.5
  moment: ^2.30.1
  naive-ui: ^2.41.0
  npm-run-all: ^4.1.5
  oxlint: ^0.16.10
  pdfjs-dist: ^5.2.133
  pinia: ^3.0.2
  pinia-plugin-persistedstate: ^4.3.0
  pino: ^9.6.0
  postcss: ^8.5.3
  postcss-html: ^1.8.0
  postcss-less: ^6.0.0
  postcss-scss: ^4.0.9
  prettier: ^3.5.3
  quasar: ^2.18.1
  release-it: ^19.0.2
  rimraf: ^6.0.1
  roboto-fontface: ^0.10.0
  rollup: ^4.40.2
  rollup-plugin-copy: ^3.5.0
  rollup-plugin-delete: ^3.0.1
  rollup-plugin-dts: ^6.2.1
  rollup-plugin-vue: ^6.0.0
  sass: ^1.87.0
  sockjs-client: ^1.6.1
  stomp-client: ^0.9.0
  stompjs: ^2.3.3
  stylelint: ^16.19.1
  stylelint-config-recommended-less: ^3.0.1
  stylelint-config-recommended-scss: ^15.0.0
  stylelint-config-standard: ^38.0.0
  stylelint-config-standard-vue: ^1.0.0
  stylelint-less: ^3.0.1
  stylelint-order: ^7.0.0
  stylelint-scss: ^6.12.0
  sucrase: ^3.35.0
  terser: ^5.39.0
  through2: ^4.0.2
  tslib: ^2.8.1
  typescript: ^5.8.3
  unocss: ^66.1.1
  unocss-preset-autoprefixer: ^0.0.9
  unocss-preset-weapp: ^66.0.1
  unplugin-auto-import: ^19.2.0
  unplugin-fonts: ^1.3.1
  unplugin-vue-components: ^28.5.0
  unplugin-vue-router: ^0.12.0
  vee-validate: ^4.15.0
  vinyl: ^3.0.0
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.3
  vite-plugin-static-copy: ^3.0.0
  vite-plugin-vue-devtools: ^7.7.6
  vite-plugin-vuetify: ^2.1.1
  vitepress: ^1.6.3
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-demi: ^0.14.10
  vue-eslint-parser: ^10.1.3
  vue-i18n: ^11.1.3
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  vuetify: ^3.8.4
  ws: ^8.18.2
  yup: ^1.6.1
  zod: ^3.24.4
