packages:
  - vue
  - design
  - 'configs/*'
  - shared
  - external
  - types
  - 'psdk/*'
  - 'ext/*'
  - req
  - ui
catalog:
  '@date-io/dayjs': ^3.2.0
  '@tsconfig/node22': ^22.0.1
  '@varlet/ui': ^3.10.9
  autoprefixer: ^10.4.21
  dayjs: ^1.11.13
  element-plus: ^2.10.2
  libarchive.js: ^2.0.2
  lodash-es: ^4.17.21
  npm-run-all2: ^8.0.4
  pdfjs-dist: ^5.3.31
  prettier: ^3.5.3
  sass: ^1.89.2
  turbo: ^2.5.4
  typescript: ^5.8.3
  unplugin-auto-import: ^19.3.0
  unplugin-fonts: ^1.3.1
  unplugin-vue-components: ^28.7.0
  unplugin-vue-router: ^0.12.0
catalogs:
  cssnano:
    cssnano: ^7.0.7
    cssnano-preset-advanced: ^7.0.7
  eslint:
    '@antfu/eslint-config': ^4.15.0
    '@eslint/js': ^9.29.0
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.5.1
    eslint: ^9.29.0
    eslint-plugin-prettier: ^5.5.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-vue: ^10.2.0
    typescript-eslint: ^8.34.1
  gulp:
    '@types/gulp': ^4.0.17
    '@types/gulp-autoprefixer': ^0.0.37
    '@types/gulp-postcss': ^8.0.6
    '@types/gulp-sass': ^5.0.4
    gulp: ^5.0.1
    gulp-postcss: ^10.0.0
    gulp-sass: ^6.0.1
  iconify:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/flag': ^1.2.6
    '@iconify-json/fluent': ^1.2.25
    '@iconify-json/ion': ^1.2.3
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/simple-icons': ^1.2.39
  rollup:
    rollup: ^4.44.0
  types:
    '@types/chrome': ^0.0.326
    '@types/lodash-es': ^4.17.12
    '@types/node': ^24.0.3
  unocss:
    '@unocss/cli': ^66.2.3
    '@unocss/eslint-config': ^66.2.3
    '@unocss/postcss': ^66.2.3
    '@unocss/transformer-attributify-jsx': ^66.2.3
    '@unocss/transformer-compile-class': ^66.2.3
    unocss: ^66.2.3
  vee-validate:
    '@vee-validate/yup': ^4.15.1
    '@vee-validate/zod': ^4.15.1
    vee-validate: ^4.15.1
    yup: ^1.6.1
    zod: ^3.25.67
  vite:
    '@vitejs/plugin-vue': ^5.2.4
    '@vitejs/plugin-vue-jsx': ^4.1.2
    vite: ^6.3.5
    vite-plugin-dts: ^4.5.4
    vite-plugin-vue-devtools: ^7.7.7
  vitest:
    '@types/jsdom': ^21.1.7
    jsdom: ^26.1.0
    vitest: ^3.2.4
  vue:
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.7.0
    vue: ^3.5.17
    vue-router: ^4.5.1
    vue-tsc: ^2.2.10
  vuetify:
    '@mdi/font': ^7.4.47
    vite-plugin-vuetify: ^2.1.1
    vuetify: ^3.8.10
  vueuse:
    '@vueuse/core': ^13.4.0
