packages:
  - vue
  - browseruse-mcp/*
  - configs/*
  - shared
  - external
  - types
  - psdk/*
  - ext/*
  - req
  - ui

catalog:
  '@changesets/cli': ^2.29.8
  '@date-io/dayjs': ^3.2.0
  '@next/eslint-plugin-next': ^16.0.3
  '@tsconfig/node22': ^22.0.5
  '@varlet/ui': ^3.13.0
  autoprefixer: ^10.4.23
  dayjs: ^1.11.19
  element-plus: ^2.13.1
  libarchive.js: ^2.0.2
  lodash-es: ^4.17.22
  npm: ^11.6.2
  npm-run-all2: ^8.0.4
  pdfjs-dist: ^5.4.530
  pnpm: ^10.27.0
  prettier: ^3.8.0
  sass: ^1.97.2
  turbo: ^2.7.4
  typescript: ^5.9.3
  unplugin-auto-import: ^21.0.0
  unplugin-fonts: ^1.4.0
  unplugin-vue-components: ^31.0.0
  unplugin-vue-router: ^0.19.2
  yarn: ^1.22.22

catalogs:
  chrome:
    '@types/chrome': ^0.1.33
    chrome-launcher: ^1.2.1
    lighthouse: ^13.0.1
  conflicts_@next/eslint-plugin-next_:
    '@next/eslint-plugin-next': ''
  conflicts_@next/eslint-plugin-next_ca:
    '@next/eslint-plugin-next': ca
  conflicts_@next/eslint-plugin-next_ca't:
    '@next/eslint-plugin-next': ca't
  conflicts_@next/eslint-plugin-next_ca'ta'lo'g:
    '@next/eslint-plugin-next': ca'ta'lo'g
  conflicts_@next/eslint-plugin-next_cata:
    '@next/eslint-plugin-next': cata
  conflicts_@next/eslint-plugin-next_catalo:
    '@next/eslint-plugin-next': catalo
  conflicts_@next/eslint-plugin-next_catalog:
    '@next/eslint-plugin-next': catalog
  conflicts_@next/eslint-plugin-next_h:
    '@next/eslint-plugin-next': ^
  conflicts_@next/eslint-plugin-next_h16:
    '@next/eslint-plugin-next': ^16
  conflicts_@next/eslint-plugin-next_h16_0:
    '@next/eslint-plugin-next': ^16.0
  conflicts_@next/eslint-plugin-next_h16_0_:
    '@next/eslint-plugin-next': ^16.0.
  cssnano:
    cssnano: ^7.1.2
    cssnano-preset-advanced: ^7.0.10
  eslint:
    '@antfu/eslint-config': ^7.0.1
    '@eslint/js': ^9.39.2
    '@next/eslint-plugin-next': ^16.1.2
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-vue: ^10.6.2
    typescript-eslint: ^8.53.0
  gulp:
    '@types/gulp': ^4.0.18
    '@types/gulp-autoprefixer': ^0.0.37
    '@types/gulp-postcss': ^8.0.6
    '@types/gulp-sass': ^6.0.0
    gulp: ^5.0.1
    gulp-postcss: ^10.0.0
    gulp-sass: ^6.0.1
  iconify:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/flag': ^1.2.10
    '@iconify-json/fluent': ^1.2.36
    '@iconify-json/ion': ^1.2.6
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/simple-icons': ^1.2.66
  mcp:
    '@modelcontextprotocol/sdk': ^1.25.2
    llm-cost: ^1.0.5
    puppeteer-core: ^24.35.0
  node:
    '@types/body-parser': ^1.19.6
    '@types/cors': ^2.8.19
    '@types/express': ^5.0.6
    '@types/node': ^25.0.8
    '@types/ws': ^8.18.1
    body-parser: ^2.2.2
    cors: ^2.8.5
    express: ^5.2.1
    pino: ^10.2.0
    ws: ^8.19.0
  rollup:
    rollup: ^4.55.1
  tsdown:
    tsdown: 0.20.0-beta.3
    unplugin-vue: ^7.1.0
    unplugin-vue-jsx: ^0.6.1
  types:
    '@types/lodash-es': ^4.17.12
  unocss:
    '@unocss/cli': ^66.6.0
    '@unocss/eslint-config': ^66.6.0
    '@unocss/postcss': ^66.6.0
    '@unocss/transformer-attributify-jsx': ^66.6.0
    '@unocss/transformer-compile-class': ^66.6.0
    unocss: ^66.6.0
  vee-validate:
    '@vee-validate/yup': ^4.15.1
    '@vee-validate/zod': ^4.15.1
    vee-validate: ^4.15.1
    yup: ^1.7.1
    zod: ^4.3.5
  vite:
    '@vitejs/plugin-vue': ^6.0.3
    '@vitejs/plugin-vue-jsx': ^5.1.3
    vite: ^7.3.1
    vite-plugin-dts: ^4.5.4
    vite-plugin-vue-devtools: ^8.0.5
  vitest:
    '@types/jsdom': ^27.0.0
    happy-dom: ^20.3.0
    jsdom: ^27.4.0
    vitest: ^4.0.17
  vue:
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    vue: ^3.5.26
    vue-router: ^4.6.4
    vue-tsc: ^3.2.2
  vuetify:
    '@mdi/font': ^7.4.47
    vite-plugin-vuetify: ^2.1.2
    vuetify: ^3.11.6
  vueuse:
    '@vueuse/core': ^14.1.0

shellEmulator: true

trustPolicy: warn

trustPolicyExclude:
  - chokidar@4.0.3
  - undici-types@6.21.0
