packages:
  - 'configs/*'
  - 'api-model-node'
  - 'api-model'
  - 'api-types'
  - '@types/*'
  - 'platform-sdk/*'
  - 'uni-app/*'
  - 'ext/*'
  - 'req'
  - 'doc'
  - 'atomic-css/*'
  - 'meta-ui-web'
  - 'meta-ui-lib'
  - 'meta-ui-web-test'
