packages:
  - vue
  - configs/*
  - shared
  - external
  - types
  - psdk/*
  - ext/*
  - req
  - ui

catalog:
  '@changesets/cli': ^2.29.7
  '@date-io/dayjs': ^3.2.0
  '@tsconfig/node22': ^22.0.2
  '@varlet/ui': ^3.11.4
  autoprefixer: ^10.4.21
  dayjs: ^1.11.18
  element-plus: ^2.11.2
  libarchive.js: ^2.0.2
  lodash-es: ^4.17.21
  npm-run-all2: ^8.0.4
  pdfjs-dist: ^5.4.149
  prettier: ^3.6.2
  sass: ^1.92.1
  turbo: ^2.5.6
  typescript: ^5.9.2
  unplugin-auto-import: ^20.1.0
  unplugin-fonts: ^1.4.0
  unplugin-vue-components: ^29.0.0
  unplugin-vue-router: ^0.15.0

catalogs:
  cssnano:
    cssnano: ^7.1.1
    cssnano-preset-advanced: ^7.0.9
  eslint:
    '@antfu/eslint-config': ^5.3.0
    '@eslint/js': ^9.35.0
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-vue: ^10.4.0
    typescript-eslint: ^8.43.0
  gulp:
    '@types/gulp': ^4.0.17
    '@types/gulp-autoprefixer': ^0.0.37
    '@types/gulp-postcss': ^8.0.6
    '@types/gulp-sass': ^5.0.4
    gulp: ^5.0.1
    gulp-postcss: ^10.0.0
    gulp-sass: ^6.0.1
  iconify:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/flag': ^1.2.9
    '@iconify-json/fluent': ^1.2.30
    '@iconify-json/ion': ^1.2.6
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/simple-icons': ^1.2.50
  rollup:
    rollup: ^4.50.1
  tsdown:
    tsdown: ^0.15.0
    unplugin-vue-jsx: ^0.6.1
  types:
    '@types/chrome': ^0.1.9
    '@types/lodash-es': ^4.17.12
    '@types/node': ^24.3.1
  unocss:
    '@unocss/cli': ^66.5.1
    '@unocss/eslint-config': ^66.5.1
    '@unocss/postcss': ^66.5.1
    '@unocss/transformer-attributify-jsx': ^66.5.1
    '@unocss/transformer-compile-class': ^66.5.1
    unocss: ^66.5.1
  vee-validate:
    '@vee-validate/yup': ^4.15.1
    '@vee-validate/zod': ^4.15.1
    vee-validate: ^4.15.1
    yup: ^1.7.0
    zod: ^4.1.5
  vite:
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.1.1
    vite: ^7.1.5
    vite-plugin-dts: ^4.5.4
    vite-plugin-vue-devtools: ^8.0.1
  vitest:
    '@types/jsdom': ^21.1.7
    happy-dom: ^18.0.1
    jsdom: ^26.1.0
    vitest: ^3.2.4
  vue:
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    vue: ^3.5.21
    vue-router: ^4.5.1
    vue-tsc: ^3.0.6
  vuetify:
    '@mdi/font': ^7.4.47
    vite-plugin-vuetify: ^2.1.2
    vuetify: ^3.9.7
  vueuse:
    '@vueuse/core': ^13.9.0
