packages:
  - vue
  - design
  - configs/*
  - shared
  - external
  - types
  - psdk/*
  - ext/*
  - req
  - ui

catalog:
  '@changesets/cli': ^2.29.6
  '@date-io/dayjs': ^3.2.0
  '@tsconfig/node22': ^22.0.2
  '@varlet/ui': ^3.11.3
  autoprefixer: ^10.4.21
  dayjs: ^1.11.13
  element-plus: ^2.10.7
  libarchive.js: ^2.0.2
  lodash-es: ^4.17.21
  npm-run-all2: ^8.0.4
  pdfjs-dist: ^5.4.54
  prettier: ^3.6.2
  sass: ^1.90.0
  turbo: ^2.5.6
  typescript: ^5.9.2
  unplugin-auto-import: ^19.3.0
  unplugin-fonts: ^1.4.0
  unplugin-vue-components: ^28.8.0
  unplugin-vue-router: ^0.14.0

catalogs:
  cssnano:
    cssnano: ^7.1.0
    cssnano-preset-advanced: ^7.0.8
  eslint:
    '@antfu/eslint-config': ^5.2.1
    '@eslint/js': ^9.33.0
    '@vue/eslint-config-prettier': ^10.2.0
    '@vue/eslint-config-typescript': ^14.6.0
    eslint: ^9.33.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-vue: ^10.4.0
    typescript-eslint: ^8.40.0
  gulp:
    '@types/gulp': ^4.0.17
    '@types/gulp-autoprefixer': ^0.0.37
    '@types/gulp-postcss': ^8.0.6
    '@types/gulp-sass': ^5.0.4
    gulp: ^5.0.1
    gulp-postcss: ^10.0.0
    gulp-sass: ^6.0.1
  iconify:
    '@iconify-json/ant-design': ^1.2.5
    '@iconify-json/flag': ^1.2.9
    '@iconify-json/fluent': ^1.2.28
    '@iconify-json/ion': ^1.2.6
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/simple-icons': ^1.2.48
  rollup:
    rollup: ^4.47.1
  tsdown:
    tsdown: ^0.14.1
  types:
    '@types/chrome': ^0.1.4
    '@types/lodash-es': ^4.17.12
    '@types/node': ^24.3.0
  unocss:
    '@unocss/cli': ^66.4.2
    '@unocss/eslint-config': ^66.4.2
    '@unocss/postcss': ^66.4.2
    '@unocss/transformer-attributify-jsx': ^66.4.2
    '@unocss/transformer-compile-class': ^66.4.2
    unocss: ^66.4.2
  vee-validate:
    '@vee-validate/yup': ^4.15.1
    '@vee-validate/zod': ^4.15.1
    vee-validate: ^4.15.1
    yup: ^1.7.0
    zod: ^4.0.17
  vite:
    '@vitejs/plugin-vue': ^6.0.1
    '@vitejs/plugin-vue-jsx': ^5.0.1
    vite: ^7.1.3
    vite-plugin-dts: ^4.5.4
    vite-plugin-vue-devtools: ^8.0.0
  vitest:
    '@types/jsdom': ^21.1.7
    jsdom: ^26.1.0
    vitest: ^3.2.4
  vue:
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    vue: ^3.5.19
    vue-router: ^4.5.1
    vue-tsc: ^3.0.6
  vuetify:
    '@mdi/font': ^7.4.47
    vite-plugin-vuetify: ^2.1.2
    vuetify: ^3.9.5
  vueuse:
    '@vueuse/core': ^13.7.0
