export { defaultJsConfig } from './javascript'
export { defaultTestConfig, defaultUnocssConfig } from './misc'
export { defaultFormatterConfig, defaultStylisticConfig } from './stylistic'
export { defaultStrictTsConfig, defaultTsConfig } from './typescript'
export { defaultVueConfig } from './vue'
