import type {Linter} from 'eslint'

/** 基础规则配置 */
export const baseRules: Linter.RulesRecord = {
  '@truenine/prefer-single-line-if': 'warn',
  '@truenine/prefer-single-line-control': 'warn',
  '@truenine/prefer-single-line-call': 'warn',
  '@truenine/prefer-concise-arrow': 'warn',
  '@truenine/prefer-guard-clause': ['warn', {minStatements: 2}],
  'antfu/if-newline': 'off',
  'antfu/curly': 'off',
  'curly': ['error', 'multi-line'],
  'arrow-body-style': ['error', 'as-needed'],
  'prefer-destructuring': ['error', {array: false, object: true}, {enforceForRenamedProperties: false}],
  'prefer-template': 'error',
  'object-shorthand': ['error', 'always'],
  'prefer-exponentiation-operator': 'error',
  'prefer-object-has-own': 'error',
  'no-else-return': ['error', {allowElseIf: false}],
  'one-var': ['error', {initialized: 'never', uninitialized: 'consecutive'}],
  'no-extra-boolean-cast': 'error',
  'no-return-await': 'error',
  'no-useless-catch': 'error',
  'no-useless-return': 'error',
  'no-useless-constructor': 'error',
  'no-useless-rename': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-escape': 'error',
  'no-useless-call': 'error',
  'no-extra-parens': ['error', 'all', {nestedBinaryExpressions: false, ignoreJSX: 'multi-line', enforceForArrowConditionals: false}],
  'unicorn/prefer-includes': 'error',
  'unicorn/prefer-string-starts-ends-with': 'error',
  'unicorn/prefer-number-properties': 'error',
  'unicorn/no-instanceof-array': 'error',
  'unicorn/prefer-at': 'error',
  'unicorn/prefer-string-slice': 'error',
  'unicorn/prefer-spread': 'error',
  'unicorn/prefer-array-flat': 'error',
  'unicorn/prefer-array-flat-map': 'error',
  'unicorn/prefer-array-find': 'error',
  'unicorn/prefer-array-some': 'error',
  'unicorn/prefer-set-has': 'error',
  'unicorn/prefer-string-replace-all': 'error',
  'unicorn/prefer-string-trim-start-end': 'error',
  'unicorn/prefer-object-from-entries': 'error',
  'unicorn/prefer-default-parameters': 'error',
  'unicorn/prefer-negative-index': 'error',
  'unicorn/prefer-math-trunc': 'error',
  'unicorn/prefer-date-now': 'error',
  'unicorn/prefer-export-from': 'warn',
  'unicorn/prefer-ternary': 'error',
  'unicorn/prefer-logical-operator-over-ternary': 'error',
  'unicorn/prefer-regexp-test': 'error',
  'unicorn/prefer-modern-dom-apis': 'error',
  'unicorn/prefer-query-selector': 'error',
  'unicorn/prefer-dom-node-append': 'error',
  'unicorn/prefer-dom-node-remove': 'error',
  'unicorn/prefer-dom-node-text-content': 'error',
  'unicorn/prefer-event-target': 'error',
  'unicorn/prefer-type-error': 'error',
  'unicorn/prefer-code-point': 'error',
  'unicorn/prefer-modern-math-apis': 'error',
  'unicorn/prefer-structured-clone': 'error',
  'unicorn/prefer-node-protocol': 'error',
  'unicorn/prefer-array-index-of': 'error',
  'unicorn/prefer-reflect-apply': 'error',
  'unicorn/prefer-set-size': 'error',
  'unicorn/text-encoding-identifier-case': 'error',
}

/** .d.ts 文件专用规则 */
export const dtsRules: Linter.RulesRecord = {'one-var': 'off'}

/** TypeScript 专用规则 */
export const typescriptRules: Linter.RulesRecord = {
  '@typescript-eslint/prefer-optional-chain': 'error',
  '@typescript-eslint/prefer-nullish-coalescing': 'error',
  '@typescript-eslint/prefer-includes': 'error',
  '@typescript-eslint/prefer-string-starts-ends-with': 'error',
  '@typescript-eslint/prefer-for-of': 'error',
  '@typescript-eslint/promise-function-async': 'error',
  '@typescript-eslint/prefer-reduce-type-parameter': 'error',
  '@typescript-eslint/prefer-regexp-exec': 'error',
  '@typescript-eslint/unbound-method': 'off',
  '@typescript-eslint/switch-exhaustiveness-check': 'off',
  '@typescript-eslint/array-type': ['error', {default: 'array'}],
  '@typescript-eslint/no-unnecessary-type-assertion': 'error',
  '@typescript-eslint/no-unnecessary-type-constraint': 'error',
  '@typescript-eslint/no-unnecessary-type-arguments': 'error',
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'error',
  '@typescript-eslint/no-unnecessary-condition': 'off',
  '@typescript-eslint/no-namespace': 'error',
  '@typescript-eslint/prefer-function-type': 'error',
  '@typescript-eslint/prefer-as-const': 'error',
}
